# This code was written by an AI assistant.

name: FTP-Deploy
on:
  push:
    branches:
      - nekoweb  # Set this to your default branch

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 161.97.73.150
        port: 54345
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}

# End of code written by an AI assistant.
